FROM golang as builder
LABEL stage=builder
WORKDIR /build
COPY . .
RUN go mod download
RUN go build -o dist/operator main.go

FROM golang as publish
WORKDIR /app
COPY --from=builder --chown=1001:1001 /build/dist/operator /usr/local/bin/operator
ENTRYPOINT [ "operator" ]
